name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and cache
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-integration-test
          push: false
          tags: deployapp-integration-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Run integration tests
        run: |
          chmod +x run_integration_tests.sh
          ./run_integration_tests.sh

  docker-image:
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: bootJar (tagged)
        if: startsWith(github.ref, 'refs/tags')
        run: |
          chmod +x ./gradlew
          ./gradlew -Pversion=${{ github.ref_name }} bootJar

      - name: bootJar (not tagged)
        if: startsWith(github.ref, 'refs/tags') != true
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: transfusion/deployapp-backend
          # flavor: latest=true
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}